spring.application.name=disaster-management
server.port=8080

spring.datasource.url=jdbc:sqlite:disaster.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=never

spring.jackson.serialization.indent_output=true